name: routo_demo
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ^3.9.2
dependencies:
  flutter:
    sdk: flutter


  #maps and location
  google_maps_flutter: ^2.5.0
  geolocator: ^12.0.0
  flutter_polyline_points: ^2.0.0




  #Api
  http: ^1.2.0
  flutter_dotenv: ^5.1.0


  #Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0


  #state management
  provider: ^6.1.2



  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  assets:
    - .env

